steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - 'gcr.io/blmayer/github.com/blmayer/tasker:${SHORT_SHA}'
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - gcr.io/blmayer/github.com/blmayer/tasker
  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - tasker
      - '--image'
      - 'gcr.io/blmayer/github.com/blmayer/tasker:${SHORT_SHA}'
      - '--region'
      - us-central1
      - '--platform'
      - managed
      - '--allow-unauthenticated'